[package]
name = "adventofcode"
version = "0.1.0"
authors = ["finleygn <finleygarton12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"